# Generated by Django 2.2.28 on 2022-08-22 20:35

from django.db import migrations, models
import django.db.models.deletion
import matter.models


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0002_auto_20220816_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matterinfo',
            name='claim_no',
            field=models.CharField(blank=True, max_length=200, verbose_name='Case/Suit Number'),
        ),
        migrations.CreateModel(
            name='MatterFactDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=250, verbose_name='Document name')),
                ('document', models.ImageField(blank=True, null=True, upload_to=matter.models.upload_to, verbose_name='')),
                ('client_type', models.CharField(max_length=200, verbose_name='Client category')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matter.MatterInfo')),
            ],
            options={
                'verbose_name': 'Document Documents',
                'verbose_name_plural': 'Document Documents',
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
