# Generated by Django 2.2.28 on 2022-08-24 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0003_auto_20220822_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matterfactdocument',
            name='client_type',
        ),
        migrations.RemoveField(
            model_name='matterfactdocument',
            name='document_name',
        ),
        migrations.AddField(
            model_name='matterfactdocument',
            name='case_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Case type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matterfactdocument',
            name='document_category',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Document category'),
        ),
        migrations.DeleteModel(
            name='SupportingDocument',
        ),
    ]
