# Generated by Django 2.2.28 on 2022-08-24 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0004_auto_20220824_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatureOfClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_of_claim', models.CharField(max_length=200, verbose_name='Title')),
                ('category', models.CharField(choices=[('Criminal', 'Criminal'), ('Civil', 'Civil')], max_length=20, verbose_name='Matter Category')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matter.MatterInfo')),
            ],
            options={
                'verbose_name': 'Matter sample',
                'verbose_name_plural': 'Matter samples',
            },
        ),
    ]
