# Generated by Django 2.2.28 on 2022-08-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0005_natureofclaim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='natureofclaim',
            options={'verbose_name': 'Matter nature', 'verbose_name_plural': 'Matter natures'},
        ),
    ]
