# Generated by Django 2.2.28 on 2022-08-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0006_auto_20220826_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natureofclaim',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Case category'),
        ),
        migrations.AlterField(
            model_name='natureofclaim',
            name='nature_of_claim',
            field=models.CharField(max_length=200, verbose_name='Nature of claim'),
        ),
    ]
