# Generated by Django 2.2.28 on 2022-08-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cperson',
            name='firstPhone',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='First Phone'),
        ),
        migrations.AlterField(
            model_name='cperson',
            name='nationality',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nationality'),
        ),
    ]
