# Generated by Django 2.2.28 on 2022-08-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20220812_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cperson',
            name='maritalStatus',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widow', 'Widow'), ('Widower', 'Widower')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cperson',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=12, null=True),
        ),
    ]
