# Generated by Django 2.2.28 on 2022-08-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20220813_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cperson',
            name='firstPhone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='First Phone'),
        ),
    ]
