# Generated by Django 2.2.28 on 2022-09-15 10:03

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20220813_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cperson',
            name='personPix',
            field=models.ImageField(blank=True, default='client/client.jpg', null=True, upload_to=contact.models.upload_to, verbose_name=''),
        ),
    ]
