# Generated by Django 2.2.28 on 2022-08-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimantDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=250, verbose_name='Category name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'claimant doc category',
                'verbose_name_plural': 'claimant doc categories',
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='DefendantDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=250, verbose_name='Category name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'defendant doc category',
                'verbose_name_plural': 'defendant doc category',
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
