# Generated by Django 2.2.28 on 2022-09-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimantdocumenttype',
            options={'ordering': ['created'], 'verbose_name': 'claimant doc category', 'verbose_name_plural': 'claimant doc categories'},
        ),
        migrations.AlterModelOptions(
            name='defendantdocumenttype',
            options={'ordering': ['created'], 'verbose_name': 'defendant doc category', 'verbose_name_plural': 'defendant doc category'},
        ),
    ]
