# Generated by Django 2.2.28 on 2022-08-01 12:18

import base.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='customuserprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuserprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='customuserprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuserprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customuserprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.svg', null=True, upload_to=base.models.upload_to, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Short biography'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='', max_length=200, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone 1'),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='other_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Other Name'),
            preserve_default=False,
        ),
    ]
