# Generated by Django 2.2.28 on 2022-08-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220801_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Home Address'),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='other_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Other Name'),
        ),
    ]
